menu:
- {name: 'publications', url: '/publications'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'fab fa-github', link: 'https://github.com/HengguangZhou'}
- {icon: 'fab fa-twitter', link: 'https://x.com/hgzhou42'}
- {icon: 'fab fa-linkedin', link: 'https://www.linkedin.com/in/hengguang-zhou/'}
- {icon: 'ai ai-cv', link: 'assets/files/cv.pdf'}

contacts:
- {name: 'Hengguang Zhou', department: 'Computer Science', institution: 'UCLA', email: 'hgzhou42@g.ucla.edu'}
